const mongoose = require('mongoose');
require('dotenv').config();
const Question = require('./models/Question');

const SUBJECT_ID = '6a442b81e9ff273d4cdbf469';
const CHAPTER_ID = '6a442b81e9ff273d4cdbf46a';
const EXAM_GROUP = 'NEET_UG';

const questions = [
  { text: "The errors in the measurement which arise due to unpredictable fluctuations in temperature and voltage supply are:", options: [{ key: "A", text: "Random errors" }, { key: "B", text: "Instrumental errors" }, { key: "C", text: "Personal errors" }, { key: "D", text: "Least count errors" }], correctKey: "A", explanation: "Unpredictable fluctuations in temperature and voltage supply cause random errors as these factors are beyond prediction and control.", difficulty: "easy" },
  { text: "A metal wire has mass (0.4 +/- 0.002) g, radius (0.3 +/- 0.001) mm and length (5 +/- 0.02) cm. The maximum possible percentage error in the measurement of density will nearly be:", options: [{ key: "A", text: "1.4%" }, { key: "B", text: "1.2%" }, { key: "C", text: "1.3%" }, { key: "D", text: "1.6%" }], correctKey: "D", explanation: "Density = m/(pi*r^2*l). Error = 0.002/0.4 + 2(0.001/0.3) + 0.02/5 = 0.5+0.67+0.4 = 1.6%", difficulty: "medium" },
  { text: "A screw gauge gives the following readings: Main scale reading: 0 mm, Circular scale reading: 52 divisions. Given that 1 mm on main scale corresponds to 100 divisions on the circular scale. The diameter of the wire is:", options: [{ key: "A", text: "0.026 cm" }, { key: "B", text: "0.26 cm" }, { key: "C", text: "0.052 cm" }, { key: "D", text: "0.52 cm" }], correctKey: "C", explanation: "LC = 1mm/100 = 0.01mm = 0.001cm. Diameter = 0 + 52(0.001) = 0.052 cm", difficulty: "easy" },
  { text: "The area of a rectangular field (in m^2) of length 55.3 m and breadth 25 m after rounding off for correct significant digits is:", options: [{ key: "A", text: "1.38 x 10^3" }, { key: "B", text: "1382" }, { key: "C", text: "1382.5" }, { key: "D", text: "14 x 10^2" }], correctKey: "D", explanation: "Area = 55.3 x 25 = 1382.5. Result should have 2 sig figs (from 25), so 14 x 10^2.", difficulty: "medium" },
  { text: "The dimensions [MLT^-2 A^-2] belong to:", options: [{ key: "A", text: "Magnetic flux" }, { key: "B", text: "Self inductance" }, { key: "C", text: "Magnetic permeability" }, { key: "D", text: "Electric permittivity" }], correctKey: "C", explanation: "Magnetic permeability has dimensions [MLT^-2 A^-2].", difficulty: "medium" },
  { text: "Plane angle and solid angle have:", options: [{ key: "A", text: "Units but no dimensions" }, { key: "B", text: "Dimensions but no units" }, { key: "C", text: "No units and no dimensions" }, { key: "D", text: "Both units and dimensions" }], correctKey: "A", explanation: "Plane angle (radian) and solid angle (steradian) have units but are dimensionless.", difficulty: "easy" },
  { text: "If E and G respectively denote energy and gravitational constant, then E/G has the dimensions of:", options: [{ key: "A", text: "[M][L^-1][T^-1]" }, { key: "B", text: "[M][L^0][T^0]" }, { key: "C", text: "[M^2][L^-2][T^-1]" }, { key: "D", text: "[M^2][L^-1][T^0]" }], correctKey: "D", explanation: "E/G = [ML^2T^-2]/[M^-1L^3T^-2] = [M^2L^-1T^0]", difficulty: "medium" },
  { text: "If force [F], acceleration [A] and time [T] are chosen as fundamental quantities, the dimensions of energy are:", options: [{ key: "A", text: "[F][A][T^2]" }, { key: "B", text: "[F][A][T^-1]" }, { key: "C", text: "[F][A^-1][T]" }, { key: "D", text: "[F][A][T]" }], correctKey: "A", explanation: "E = [ML^2T^-2]. Solving E = F^a A^b T^c gives a=1, b=1, c=2.", difficulty: "hard" },
  { text: "A screw gauge has least count of 0.01 mm and there are 50 divisions in its circular scale. The pitch of the screw gauge is:", options: [{ key: "A", text: "0.25 mm" }, { key: "B", text: "0.5 mm" }, { key: "C", text: "1.0 mm" }, { key: "D", text: "0.01 mm" }], correctKey: "B", explanation: "LC = Pitch/CSD. 0.01 = Pitch/50. Pitch = 0.5 mm.", difficulty: "easy" },
  { text: "Taking into account significant figures, what is the value of 9.99 m - 0.0099 m?", options: [{ key: "A", text: "9.98 m" }, { key: "B", text: "9.980 m" }, { key: "C", text: "9.9 m" }, { key: "D", text: "9.9801 m" }], correctKey: "A", explanation: "In subtraction, result has same decimal places as the least precise term. 9.99 has 2 decimal places, so answer = 9.98 m.", difficulty: "easy" },
  { text: "Dimensions of stress are:", options: [{ key: "A", text: "[ML^2T^-2]" }, { key: "B", text: "[ML^0T^-2]" }, { key: "C", text: "[ML^-1T^-2]" }, { key: "D", text: "[MLT^-2]" }], correctKey: "C", explanation: "Stress = Force/Area = [MLT^-2]/[L^2] = [ML^-1T^-2]", difficulty: "easy" },
  { text: "Clock readings: 1.25 s, 1.24 s, 1.27 s, 1.21 s and 1.28 s. The percentage relative error is:", options: [{ key: "A", text: "4%" }, { key: "B", text: "16%" }, { key: "C", text: "1.6%" }, { key: "D", text: "2%" }], correctKey: "C", explanation: "Mean = 1.25 s. Mean error = 0.02. % error = (0.02/1.25)x100 = 1.6%", difficulty: "medium" },
  { text: "The angle of 1 minute of arc in radian is nearly equal to:", options: [{ key: "A", text: "4.85 x 10^-4 rad" }, { key: "B", text: "4.80 x 10^-6 rad" }, { key: "C", text: "1.75 x 10^-2 rad" }, { key: "D", text: "2.91 x 10^-4 rad" }], correctKey: "D", explanation: "1 minute = pi/(60x180) radian = 2.91 x 10^-4 radian.", difficulty: "easy" },
  { text: "Percentage errors in A, B, C, D are 1%, 2%, 3%, 4%. If X = A^2 B^(1/2) / (C^(1/3) D^3), max % error in X is:", options: [{ key: "A", text: "10%" }, { key: "B", text: "16%" }, { key: "C", text: "-10%" }, { key: "D", text: "10%" }], correctKey: "B", explanation: "Error = 2(1) + 0.5(2) + (1/3)(3) + 3(4) = 2+1+1+12 = 16%", difficulty: "hard" },
  { text: "A screw gauge with LC 0.001 cm, MSR 5 mm, circular scale at 25 divisions, zero error -0.004 cm. Correct diameter is:", options: [{ key: "A", text: "0.053 cm" }, { key: "B", text: "0.525 cm" }, { key: "C", text: "0.521 cm" }, { key: "D", text: "0.529 cm" }], correctKey: "D", explanation: "Reading = 0.5 + 25(0.001) + 0.004 = 0.529 cm", difficulty: "medium" },
  { text: "Vernier caliper: 50 VSD = 49 MSD. Zero between 7.00 and 7.05 cm, 23rd vernier division coincides. Thickness is:", options: [{ key: "A", text: "7.73 cm" }, { key: "B", text: "7.23 cm" }, { key: "C", text: "7.023 cm" }, { key: "D", text: "7.073 cm" }], correctKey: "C", explanation: "LC = 1MSD - 1VSD = 0.05 - (49/50)(0.05) = 0.001 cm. Thickness = 7.00 + 23(0.001) = 7.023 cm", difficulty: "medium" },
  { text: "Using h, c and G as fundamental constants, which combination has the dimension of length?", options: [{ key: "A", text: "sqrt(hc/G)" }, { key: "B", text: "sqrt(Gc/h^(3/2))" }, { key: "C", text: "sqrt(hG/c^(3/2))" }, { key: "D", text: "sqrt(hG/c^(5/2))" }], correctKey: "C", explanation: "Dimensional analysis gives L = sqrt(hG/c^3), which matches option C.", difficulty: "hard" },
  { text: "If energy (E), velocity (V) and time (T) are fundamental quantities, the dimensional formula of surface tension is:", options: [{ key: "A", text: "[EV^-1T^-2]" }, { key: "B", text: "[EV^-2T^-2]" }, { key: "C", text: "[E^-2V^-1T^-3]" }, { key: "D", text: "[EV^-2T^-1]" }], correctKey: "B", explanation: "Surface tension [MT^-2] = E^a V^b T^c. Solving: a=1, b=-2, c=-2.", difficulty: "hard" },
  { text: "Critical velocity vc of liquid through a tube: vc = eta^x rho^y r^z. Values of x, y, z are:", options: [{ key: "A", text: "1, 1, 1" }, { key: "B", text: "1, -1, -1" }, { key: "C", text: "-1, -1, 1" }, { key: "D", text: "-1, -1, -1" }], correctKey: "B", explanation: "[LT^-1] = [ML^-1T^-1]^x [ML^-3]^y [L]^z. Solving: x=1, y=-1, z=-1.", difficulty: "hard" },
  { text: "If Force (F), Velocity (V) and Time (T) are fundamental units, dimensions of mass are:", options: [{ key: "A", text: "[FV^-1T]" }, { key: "B", text: "[FVT^-2]" }, { key: "C", text: "[FV^-1T^-1]" }, { key: "D", text: "[FV^-1T]" }], correctKey: "D", explanation: "Mass = Force/Acceleration = Force/(Velocity/Time) = [FV^-1T]", difficulty: "medium" },
  { text: "P = a^3 b^2/(cd). Percentage errors in a,b,c,d are 1%,2%,3%,4%. Percentage error in P is:", options: [{ key: "A", text: "4%" }, { key: "B", text: "14%" }, { key: "C", text: "10%" }, { key: "D", text: "7%" }], correctKey: "B", explanation: "Error = 3(1) + 2(2) + 3 + 4 = 3+4+3+4 = 14%", difficulty: "medium" },
];

async function upload() {
  await mongoose.connect(process.env.MONGO_URI);
  console.log('Connected to MongoDB');
  const existing = await Question.countDocuments({ chapter: CHAPTER_ID });
  console.log('Existing questions for this chapter:', existing);
  const docs = questions.map(q => ({ subject: SUBJECT_ID, chapter: CHAPTER_ID, examGroup: EXAM_GROUP, ...q }));
  const result = await Question.insertMany(docs);
  console.log('Inserted', result.length, 'questions for Units and Measurements (Physics)');
  process.exit(0);
}
upload().catch(e => { console.error(e); process.exit(1); });
